export { IntervalsClient, type IntervalsClientOptions } from "./client.js";
export { type AuthConfig, type ApiKeyAuth, type BearerAuth } from "./auth.js";
export { type Result, type ApiError, type ValidationIssue, ok, err, isOk, isErr, unwrap, mapResult, toValidationIssues } from "./result.js";
export { decode, decodeArray } from "./decode.js";
export { camelCaseKeys, snakeCaseKeys, toCamelCase, toSnakeCase } from "./transform.js";
export { type RetryOptions } from "./retry.js";
export { type Hooks } from "./hooks.js";
export { AthleteResource } from "./resources/athlete.js";
export { ActivitiesResource } from "./resources/activities.js";
export { WellnessResource } from "./resources/wellness.js";
export { EventsResource } from "./resources/events.js";
export { WorkoutsResource } from "./resources/workouts.js";
export { PowerCurvesResource } from "./resources/power-curves.js";
export { FoldersResource } from "./resources/folders.js";
export { GearResource } from "./resources/gear.js";
export { AthleteSchema, type Athlete, decodeAthlete } from "./schemas/athlete.js";
export { ActivitySchema, type Activity, decodeActivity, decodeActivities } from "./schemas/activity.js";
export { WellnessSchema, type WellnessRecord, decodeWellness } from "./schemas/wellness.js";
export { EventSchema, type Event, decodeEvent, decodeEvents } from "./schemas/event.js";
export { WorkoutSchema, type Workout } from "./schemas/workout.js";
export { PowerCurveSchema, type PowerCurve } from "./schemas/power-curve.js";
export type { paths, components, operations } from "./generated/schema.js";
